### PR TITLE
connect to daemon specified in env vars

### LINKED ISSUE #65: DOCKER_CONNECTION issue on OSX due to no docker.sock, it uses a VirutalBox VM
There is no docker.sock for use with OSX since it's inside the VM for Docker, if this is still able to work maybe supply a document or note on how to change the value for OSX.

### PR DESCRIPTION
**Pull request by TomasTomecek**
Fixes #65

### CODE REVIEW

**Comment by goldmann** [comment]
Thanks for this PR, but I guess the documentation needs to be redone. It mentions the earlier `DOCKER_CONNECTION` env var, but it's not available anymore.

**Comment by TomasTomecek** [comment]
you're right, I [thought](https://github.com/docker/docker-py/blob/453ab066702b272be42a39d7b4e164d90f6e81be/docker/utils/utils.py#L485) the variable is named the same; will also make it backwards compat

**Comment by TomasTomecek** [comment]
rebased, updated, tests seem to pass; landscape is in limbo, as usual

**Comment by goldmann** [comment]
I'll merge this but I'll do a small refactor later to do proper logging. I'm also not sure if backwards compatibility is required since this release will introduce a few breaking changes either case. I'll decide later.

**Comment by TomasTomecek** [comment]
feel free to remove the backwards compat code; my point with this patch is just `docker.utils.kwargs_from_env`

**Pull request merged**
