### PR TITLE
Cleanup temp dir even when things go wrong

### PR DESCRIPTION
**Pull request by rhcarvalho**
If there's any exception while executing those multiple steps in `run`, the temp directory is left intact. I believe that's not intentional.

This patch makes `run` always remove the temp dir.

### CODE REVIEW

**Comment by goldmann** [comment]
I don't think we should do it. the temp dir is a good place to look what was done and debug where it failed.

**Comment by rhcarvalho** [comment]
The two occasions in which squash failed for me, there were no benefit of having left overs:
- IOError -- no space left in disk
- MemoryError -- exhausted RAM in [`_load_image`](https://github.com/goldmann/docker-scripts/blob/23b275c21fc1f92a6b00070109c6ee43dba6c138/docker_scripts/squash.py#L191)

In both cases the traceback was enough info, and I'd have to find the temp dir and remove it manually.
But of course you might have other reasons to keep it.

**Comment by goldmann** [comment]
Hmm, instead of your propsed approach (clean every time an error occures) - we could catch these specific errors and cleanup the tmp dir. This would allow us to give a proper hint to the user too.

**Comment by rhcarvalho** [comment]
Yes, not bad handling those exceptions. Perhaps it would even be possible to create the new tarball by piping the output of the old ones into the new one without writing intermediate files?

**Comment by goldmann** [comment]
That's a possibility, please open a RFE for it.

**Pull request closed without merging**
