### PR TITLE
add __version__

### PR DESCRIPTION
**Pull request by TomasTomecek**
to comply with PEP 0396

Related https://github.com/projectatomic/atomic-reactor/pull/324#issuecomment-140335471

### CODE REVIEW

**Comment by goldmann** [comment]
@TomasTomecek Basically I'm cool with this, but this broke the build :)

**Comment by TomasTomecek** [comment]
Looks like that's what the pep is about: once you specify `__version__`, python will then link the content of that attribute to `<module>.version`

**Comment by goldmann** [comment]
I'm so glad we have a CI :)

**Comment by TomasTomecek** [comment]
now or never

**Comment by TomasTomecek** [comment]
CI++ you're right

3 line patch turned into 17 lines

**Comment by goldmann** [comment]
Merging with pleasure :)

**Comment by TomasTomecek** [comment]
Thank you! (now we can log in reactor version of `docker-scripts` :)

**Pull request merged**
